server:
  port: 8080
spring:
  application:
    name: hystrix-client
  cloud:
    loadbalancer:
      retry:
        enabled: true

product:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0  # default 0
    MaxAutoRetriesNextServer: 1 # default 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

#feign:
#  hystrix:
#    enabled: true
